Catkin-ProjectName: gencpp
Version: 0.3.0
Description: ros message generation, cpp style.
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Dirk Thomas <dthomas@willowgarage.com>
Homepage: http://www.ros.org/wiki/roscpp

Depends: catkin, genmsg

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: cpp
